### PR TITLE
Wildfly timeout

### PR DESCRIPTION
**Pull request by ericnormand**
[Pivotal Card](https://www.pivotaltracker.com/story/show/91975122)

Now didor will look for wildfly for at most 30 seconds, failing if it takes that long.

### CODE REVIEW

**Comment by ericnormand** [comment]
Ping @cap10morgan

**Comment by cap10morgan** [comment]
LGTM

**Comment by cap10morgan** [comment]
Needs master merge.

**Comment by ericnormand** [comment]
Testing it.

**Pull request merged**
