### PR TITLE
[EN] Use the auto-generated ENV VARS from docker linking.

### PR DESCRIPTION
**Pull request by ericnormand**
These replace WILDFLY_ADMIN_USER with WILDFLY_ENV_ADMIN_USERNAME and
WILDFLY_ADMIN_PASSWORD with WILDFLY_ENV_ADMIN_PASSWORD.

Now the env vars do not need to be passed in explicitly in the service.

### CODE REVIEW

**Comment by ericnormand** [comment]
Ping @tie-rack . You suggested this change so you probably want to see it.

**Comment by cap10morgan** [comment]
:+1: Thanks @ericnormand and good suggestion, @tie-rack.

**Comment by ericnormand** [comment]
Does the thumbs up represent a LGTM?

**Comment by tie-rack** [comment]
:thumbsup:

**Pull request merged**
